<?php
/**
 * Content data: image library, services, service areas and FAQs.
 */

if (basename($_SERVER['SCRIPT_FILENAME'] ?? '') === 'data.php') {
    http_response_code(403);
    exit;
}

/*
 * IMAGE LIBRARY (stock photos from Pexels — free for commercial use, no attribution required).
 * To swap a stock photo for a real project photo, replace the value with a local path,
 * e.g. 'hero' => ['src' => 'assets/img/projects/shower-01.jpg', 'alt' => '...'].
 * Local files should be at least 1600px wide.
 */
$IMAGES = [
    'hero'        => ['pexels' => 11701114, 'alt' => 'Modern bathroom with a glass walk-in shower and floor-to-ceiling tile'],
    'shower-1'    => ['pexels' => 6436787,  'alt' => 'Bright bathroom with frameless glass shower and tiled walls'],
    'shower-2'    => ['pexels' => 19227243, 'alt' => 'Luxury bathroom with a spacious tiled walk-in shower'],
    'shower-3'    => ['pexels' => 6957087,  'alt' => 'Modern bathroom with a tiled shower enclosure'],
    'shower-4'    => ['pexels' => 6436770,  'alt' => 'Contemporary bathroom with ceramic tile and glass shower'],
    'bath-1'      => ['pexels' => 16113325, 'alt' => 'Modern bathroom interior with large-format wall tile'],
    'bath-2'      => ['pexels' => 6032203,  'alt' => 'Stylish bathroom with marble-look tile and glass elements'],
    'bath-3'      => ['pexels' => 18246436, 'alt' => 'Elegant bathroom remodel with tiled walls and floor'],
    'bath-4'      => ['pexels' => 7040699,  'alt' => 'Bathroom interior design with clean tile finishes'],
    'kitchen-1'   => ['pexels' => 8031909,  'alt' => 'Kitchen with subway tile backsplash and white cabinets'],
    'kitchen-2'   => ['pexels' => 24245773, 'alt' => 'Kitchen with white tile backsplash and cupboards'],
    'kitchen-3'   => ['pexels' => 15062155, 'alt' => 'Modern kitchen with tile backsplash and stainless appliances'],
    'floor-1'     => ['pexels' => 9690090,  'alt' => 'Tile installers laying floor tile'],
    'floor-2'     => ['pexels' => 17181934, 'alt' => 'Bright living room with large porcelain floor tile'],
    'install'     => ['pexels' => 29181495, 'alt' => 'Wall tile installation in progress'],
    // Local photos: 'local' maps width => file (used to build a responsive srcset)
    'about-story' => ['local' => [480 => 'assets/img/projects/kitchen-backsplash-remodel-480.webp', 667 => 'assets/img/projects/kitchen-backsplash-remodel-667.webp'],
                      'alt' => 'Kitchen remodel with marble-look backsplash and wood-look plank flooring'],
    'home-story'  => ['local' => [480 => 'assets/img/projects/floor-installation-480.webp', 1000 => 'assets/img/projects/floor-installation-1000.webp'],
                      'alt' => 'Installer laying wood-look plank flooring'],
    'fireplace-1' => ['pexels' => 6035369,  'alt' => 'Living room with a tiled fireplace surround'],
    'fireplace-2' => ['pexels' => 24827078, 'alt' => 'Fireplace with modern tile surround in a living room'],
    'fireplace-3' => ['pexels' => 28345539, 'alt' => 'Stone-look fireplace wall in a living room'],
    'texture'     => ['pexels' => 1144871,  'alt' => 'White ceramic tile detail'],
];

/*
 * SERVICES — each one has its own page generated by includes/service-template.php
 */
$SERVICES = [
    'bathroom-shower-remodeling' => [
        'nav'      => 'Showers & Bathrooms',
        'short'    => 'Custom tile showers, tub surrounds and complete bathroom tile remodels.',
        'icon'     => 'shower',
        'image'    => 'shower-2',
        'title'    => 'Tile Shower & Bathroom Remodeling in Manchester, NH',
        'meta'     => 'Custom tile showers, walk-in showers, tub surrounds and full bathroom tile remodels in Manchester & Southern NH. Free estimates + 1-year warranty.',
        'h1'       => 'Tile Showers & Bathroom Remodeling',
        'kicker'   => 'Our most requested service',
        'lead'     => 'From a simple tub surround to a full walk-in shower with niches and a bench, we build bathrooms that look sharp on day one and stay watertight for years.',
        'intro'    => [
            'The bathroom is where tile work is put to the test every single day: water, steam, cleaning products and constant use. That is why every shower we build starts with proper preparation — a solid substrate, a reliable waterproofing system and correct slopes to the drain — before a single tile goes on the wall.',
            'With more than 20 years of hands-on tile experience, our team handles the details that make a bathroom feel custom: perfectly aligned grout lines, clean cuts around valves and fixtures, mitered or trimmed edges, recessed niches and a finish that is easy to keep clean.',
        ],
        'features' => [
            'Walk-in and curbless tile showers',
            'Tub-to-shower conversions',
            'Tub surrounds and wainscoting',
            'Shower niches, benches and ledges',
            'Bathroom floor tile (including heated-floor prep)',
            'Large-format, porcelain, ceramic, marble-look and mosaic tile',
            'Waterproofing and shower pan systems',
            'Grout and silicone finishing for a clean, lasting seal',
        ],
        'gallery'  => ['shower-1', 'shower-3', 'bath-2', 'shower-4'],
        'faqs'     => [
            ['How long does a tile shower take?', 'It depends on the size of the shower, the tile you choose and the prep required. We give you a clear timeline during your free estimate — and we are known for working fast without cutting corners.'],
            ['Do you waterproof the shower before tiling?', 'Yes. Every shower gets a waterproofing system and a properly sloped base before tile is installed. It is the most important step of the job and we never skip it.'],
            ['Can you convert my bathtub into a walk-in shower?', 'Yes. Tub-to-shower conversions are one of the most popular upgrades we do. We will look at your space during the free estimate and walk you through the options.'],
        ],
    ],
    'tile-flooring' => [
        'nav'      => 'Tile Flooring',
        'short'    => 'Porcelain and ceramic floor tile for kitchens, baths, entries and more.',
        'icon'     => 'floor',
        'image'    => 'floor-2',
        'title'    => 'Floor Tile Installation in Manchester, NH',
        'meta'     => 'Floor tile installation in Manchester & Southern NH — porcelain, ceramic and large-format tile for kitchens, baths and entries. Free estimates.',
        'h1'       => 'Floor Tile Installation',
        'kicker'   => 'Flat, level and built to last',
        'lead'     => 'A great tile floor starts underneath. We prepare the subfloor, plan the layout and set every tile flat and level for a floor you will enjoy for decades.',
        'intro'    => [
            'Tile is one of the most durable floor finishes you can choose, but only when it is installed correctly. Uneven subfloors, poor coverage and bad layout planning are the main causes of cracked tiles and loose grout. We take care of each of those steps so your floor stays solid.',
            'We install porcelain, ceramic and large-format tile in kitchens, bathrooms, laundry rooms, entryways and mudrooms — and we can also install luxury vinyl plank when it is the better fit for your space.',
        ],
        'features' => [
            'Kitchen, bathroom, entry and mudroom floors',
            'Porcelain, ceramic and natural-stone-look tile',
            'Large-format tile with lippage control',
            'Wood-look plank tile and patterned layouts',
            'Subfloor preparation and leveling',
            'Uncoupling membranes to prevent cracking',
            'Baseboard tile and transitions',
            'Luxury vinyl plank (LVP) installation',
        ],
        'gallery'  => ['floor-1', 'bath-1', 'kitchen-3', 'texture'],
        'faqs'     => [
            ['Can you install tile over my existing floor?', 'Sometimes. It depends on the condition and height of the existing floor. We check it during the free estimate and recommend the option that gives you the longest-lasting result.'],
            ['Do you install hardwood?', 'No. We specialize in tile and also install luxury vinyl plank. If you love the look of wood, wood-look porcelain tile is a great, water-resistant alternative.'],
            ['What is the best tile for a kitchen floor?', 'Porcelain is usually the best choice for kitchens because it is dense, durable and resists stains and moisture. We will help you choose the right size and finish for your space.'],
        ],
    ],
    'kitchen-backsplash' => [
        'nav'      => 'Kitchen Backsplash',
        'short'    => 'Subway, mosaic, herringbone and large-format backsplash installation.',
        'icon'     => 'backsplash',
        'image'    => 'kitchen-1',
        'title'    => 'Kitchen Backsplash Tile Installation in Manchester, NH',
        'meta'     => 'Kitchen backsplash installation in Manchester & Southern NH — subway, herringbone, mosaic and large-format tile, cut clean and straight. Free estimates.',
        'h1'       => 'Kitchen Backsplash Installation',
        'kicker'   => 'The fastest way to transform a kitchen',
        'lead'     => 'A new backsplash changes the whole look of your kitchen in a short time. We make sure the lines are straight, the cuts around outlets are clean and the edges are finished right.',
        'intro'    => [
            'The backsplash is right at eye level, so small mistakes are easy to see. Uneven spacing, crooked lines or rough cuts around outlets and windows can ruin an otherwise beautiful kitchen. Our fine-finish approach is what our clients notice first.',
            'Whether you want classic white subway tile, a herringbone or chevron pattern, glass mosaic or a sleek large-format slab look, we plan the layout so the pattern is centered and balanced across your counters.',
        ],
        'features' => [
            'Subway tile in straight, offset or vertical stack',
            'Herringbone and chevron patterns',
            'Glass, stone and ceramic mosaics',
            'Large-format and slab-look backsplash',
            'Clean cuts around outlets, windows and hoods',
            'Metal or tile edge trims for a finished look',
            'Accent walls and coffee-bar backsplashes',
            'Removal of old backsplash when needed',
        ],
        'gallery'  => ['kitchen-2', 'kitchen-3', 'kitchen-1', 'texture'],
        'faqs'     => [
            ['How long does a backsplash installation take?', 'Most kitchen backsplashes are completed quickly — often in one to two days depending on size and pattern. We confirm the schedule during your free estimate.'],
            ['Do I need to buy the tile before the estimate?', 'No. We can visit first, measure your kitchen and help you understand how much tile you need and which patterns work best for your space.'],
            ['Can you remove my old backsplash?', 'Yes. We can remove the existing backsplash, repair the wall and prepare it for new tile.'],
        ],
    ],
    'fireplace-tile' => [
        'nav'      => 'Fireplace Tile',
        'short'    => 'Tile fireplace surrounds, hearths and floor-to-ceiling feature walls.',
        'icon'     => 'fireplace',
        'image'    => 'fireplace-1',
        'title'    => 'Fireplace Tile Surrounds & Hearths in Manchester, NH',
        'meta'     => 'Fireplace tile surrounds, hearths and floor-to-ceiling feature walls in Manchester & Southern NH. Porcelain, stone-look and marble-look tile. Free estimates.',
        'h1'       => 'Fireplace Tile Surrounds',
        'kicker'   => 'Turn your fireplace into a focal point',
        'lead'     => 'A tiled fireplace surround or feature wall instantly upgrades your living room. We handle the layout, the cuts and the finish so it looks like it was designed for your home.',
        'intro'    => [
            'Fireplaces are the natural focal point of a room, and tile is one of the best ways to make them stand out. Large-format porcelain, marble-look slabs, stacked stone-look tile or a classic pattern — each option needs careful layout to look balanced and intentional.',
            'We prepare the surface, plan the tile layout around the firebox and mantel, and finish every edge cleanly so your fireplace becomes the highlight of your home.',
        ],
        'features' => [
            'Fireplace surrounds and facing',
            'Hearth tile',
            'Floor-to-ceiling feature walls',
            'Large-format and marble-look porcelain',
            'Stacked stone-look tile',
            'Book-matched and patterned layouts',
            'Clean mitered corners and edge trims',
            'Removal of outdated tile or brick facing',
        ],
        'gallery'  => ['fireplace-2', 'fireplace-3', 'floor-2', 'texture'],
        'faqs'     => [
            ['Can you tile over my existing brick fireplace?', 'In many cases, yes. We check the condition of the existing surface during the estimate and recommend the right preparation for a secure installation.'],
            ['What tile works best for a fireplace?', 'Porcelain and natural-stone-look tiles are popular because they handle heat well and come in large formats. We will help you choose a tile that fits your style and your fireplace type.'],
            ['Do you also build the mantel?', 'Our focus is tile. We can work around your existing mantel or coordinate with the installer of a new one.'],
        ],
    ],
];

/*
 * SERVICE AREA — New Hampshire only (~50 miles from Manchester). No MA or ME.
 */
$CITIES = [
    'Manchester', 'Bedford', 'Goffstown', 'Hooksett', 'Auburn', 'Londonderry', 'Derry',
    'Merrimack', 'Litchfield', 'Hudson', 'Nashua', 'Amherst', 'Milford', 'Hollis',
    'Windham', 'Salem', 'Pelham', 'Chester', 'Candia', 'Raymond', 'Hampstead',
    'Atkinson', 'Plaistow', 'Concord', 'Bow', 'Pembroke', 'Weare', 'New Boston',
    'Epping', 'Exeter', 'Brookline', 'Allenstown',
];

/*
 * General FAQs (home page + FAQPage schema)
 */
$FAQS = [
    ['Is the estimate really free?', 'Yes — 100% free, with no obligation, anywhere in our New Hampshire service area. Many contractors charge just to come out and quote; we don\'t.'],
    ['What areas do you serve?', 'We serve Manchester and cities within about 50 miles in New Hampshire, including Nashua, Concord, Bedford, Londonderry, Derry, Merrimack, Salem, Hudson and Exeter. We do not work in Massachusetts or Maine.'],
    ['Do you offer a warranty?', 'Yes. Every job includes a 1-year warranty covering workmanship and product.'],
    ['What is the best way to contact you?', 'Text us at ' . PHONE_DISPLAY . ' or fill out the estimate form. Texting is the fastest way to share photos of your space and schedule your free estimate.'],
    ['What payment methods do you accept?', 'We accept Zelle, cash, check and Venmo.'],
    ['What types of tile do you install?', 'Porcelain, ceramic, large-format, mosaic, glass, marble-look and natural-stone-look tile for showers, bathrooms, floors, backsplashes and fireplaces.'],
];
