import { readFileSync } from 'node:fs';
import { ICONS } from './icons-data.mjs';
import { SITE, smsHref, telHref, waHref } from '../config.mjs';

const IMAGES = JSON.parse(readFileSync(new URL('../data/images.json', import.meta.url), 'utf8'));

export const esc = (s) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/** Inline SVG icon. Decorative by default (aria-hidden). */
export function icon(name, { size = 20, cls = '' } = {}) {
  const ic = ICONS[name];
  if (!ic) throw new Error(`Unknown icon: ${name}`);
  const paint =
    ic.kind === 'fill'
      ? 'fill="currentColor"'
      : 'fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"';
  return `<svg class="icon ${cls}" width="${size}" height="${size}" viewBox="0 0 24 24" ${paint} aria-hidden="true" focusable="false">${ic.inner}</svg>`;
}

/**
 * Responsive <picture> with AVIF + WebP sources generated by scripts/optimize-images.mjs.
 * Width/height attributes come from the source ratio so the browser can reserve space (CLS).
 */
export function pic(key, { alt, sizes = '100vw', eager = false, cls = '', imgCls = '', position } = {}) {
  const meta = IMAGES[key];
  if (!meta) throw new Error(`Unknown image: ${key}`);
  if (alt === undefined) throw new Error(`Missing alt for image: ${key}`);
  const set = (ext) => meta.widths.map((w) => `/assets/img/${key}-${w}.${ext} ${w}w`).join(', ');
  const fallbackW = meta.widths[Math.min(1, meta.widths.length - 1)];
  const h = Math.round((meta.height / meta.width) * fallbackW);
  const style = position ? ` style="object-position:${position}"` : '';
  return `<picture class="${cls}">
  <source type="image/avif" srcset="${set('avif')}" sizes="${sizes}">
  <source type="image/webp" srcset="${set('webp')}" sizes="${sizes}">
  <img src="/assets/img/${key}-${fallbackW}.webp" width="${fallbackW}" height="${h}" alt="${esc(alt)}" class="${imgCls}"${style} ${
    eager ? 'fetchpriority="high" decoding="async"' : 'loading="lazy" decoding="async"'
  }>
</picture>`;
}

export function imagePreload(key, sizes) {
  const meta = IMAGES[key];
  const set = meta.widths.map((w) => `/assets/img/${key}-${w}.avif ${w}w`).join(', ');
  return `<link rel="preload" as="image" type="image/avif" imagesrcset="${set}" imagesizes="${sizes}" fetchpriority="high">`;
}

export const imageUrl = (key, w) => `${SITE.url}/assets/img/${key}-${w ?? IMAGES[key].widths.at(-1)}.webp`;

/* ---------- Contact buttons ---------- */

export function btnText(label, body, { variant = 'warm', cls = '' } = {}) {
  return `<a class="btn btn--${variant} ${cls}" href="${esc(smsHref(body))}" data-cta="sms">${icon('message-square-text')}<span>${label}</span></a>`;
}
export function btnCall(label = `Call ${SITE.phoneDisplay}`, { variant = 'ghost', cls = '' } = {}) {
  return `<a class="btn btn--${variant} ${cls}" href="${telHref()}" data-cta="call">${icon('phone')}<span>${label}</span></a>`;
}
export function btnWhatsApp(label = 'WhatsApp', text, { variant = 'ghost', cls = '' } = {}) {
  return `<a class="btn btn--${variant} ${cls}" href="${esc(waHref(text))}" target="_blank" rel="noopener noreferrer" data-cta="whatsapp">${icon('whatsapp')}<span>${label}</span><span class="sr-only"> (opens WhatsApp in a new tab)</span></a>`;
}

/** Strip tags for JSON-LD text. */
export const plain = (s) => s.replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();

export const jsonLd = (graph) =>
  `<script type="application/ld+json">${JSON.stringify({ '@context': 'https://schema.org', '@graph': graph }).replace(/</g, '\\u003c')}</script>`;
