<?php
// Project photos: slug => [category, alt text, width, height]. Files live in assets/img/work/.
return [
  ['wood-look-tile-walk-in-shower-bench-window', 'shower', 'Walk-in shower with wood-look porcelain wall tile, built-in bench and pebble shower floor', 900, 1200],
  ['walk-in-shower-wood-look-tile-bench', 'shower', 'Finished walk-in shower with tiled bench, pebble floor and large-format floor tile', 900, 1200],
  ['shower-wood-look-tile-glass-block-window', 'shower', 'Shower remodel with wood-look tile walls and glass block window', 900, 1200],
  ['white-subway-tile-shower-mosaic-feature', 'shower', 'White subway tile shower with mosaic feature panel, niches and pebble floor', 900, 1200],
  ['subway-tile-shower-corner-shelf', 'shower', 'Subway tile shower with mosaic accent wall and corner shelf', 900, 1200],
  ['marble-look-shower-bench-mosaic-niche', 'shower', 'Marble-look porcelain shower with tiled bench and mosaic niche', 900, 1200],
  ['marble-look-shower-pebble-floor', 'shower', 'Marble-look shower with pebble mosaic floor and bench', 900, 1200],
  ['white-marble-look-shower-niche-bench', 'shower', 'White marble-look shower with recessed niche and floating corner bench', 900, 1200],
  ['marble-shower-quartz-curb', 'shower', 'Marble-look shower with long niche and solid surface curb', 900, 1200],
  ['marble-look-shower-corner-seat', 'shower', 'Marble-look porcelain shower with corner seat and matching floor', 900, 1200],
  ['mosaic-shower-floor-corner-shelves', 'shower', 'Shower with square mosaic floor, corner shelves and marble-look walls', 900, 1200],
  ['beige-porcelain-shower-niche', 'shower', 'Beige porcelain tile shower with framed niche and corner bench', 900, 1200],
  ['beige-tile-shower-niche-seat', 'shower', 'Beige tile shower with recessed niche, corner seat and mosaic floor', 900, 1200],
  ['marble-shower-vertical-mosaic-accent', 'shower', 'Marble-look shower with vertical glass mosaic accent strip and niche', 900, 1200],
  ['bathroom-shower-mosaic-floor-niche', 'shower', 'Bathroom remodel with marble-look shower, mosaic floor and wall niche', 900, 1200],
  ['walk-in-shower-terrazzo-floor', 'shower', 'Walk-in shower with large marble-look wall tile and terrazzo-style floor', 900, 1200],
  ['terrazzo-look-shower-pan', 'shower', 'Terrazzo-look shower floor with quartz curb', 900, 1200],
  ['curbless-shower-marble-hex-floor', 'shower', 'Large walk-in shower with marble-look walls and dark hexagon floor', 900, 1200],
  ['walk-in-shower-arched-window', 'shower', 'Walk-in shower with marble-look tile and arched window', 900, 1200],
  ['hexagon-mosaic-shower-floor', 'shower', 'Two-tone hexagon mosaic shower floor with porcelain walls', 900, 1200],
  ['hexagon-shower-floor-quartz-curb', 'shower', 'Hexagon tile shower pan with quartz curb', 900, 1200],
  ['double-shower-niche-detail', 'shower', 'Detail of double recessed shower niche with mitered edges', 900, 1200],
  ['blue-subway-tile-shower', 'bathroom', 'Blue glossy subway tile shower with niche and hexagon floor', 900, 1200],
  ['blue-subway-tile-shower-pan', 'bathroom', 'Blue subway tile walls with white mosaic shower floor', 900, 1200],
  ['marble-look-tub-surround-niche', 'bathroom', 'Marble-look tile tub surround with vertical niche', 900, 1200],
  ['bathtub-surround-marble-tile', 'bathroom', 'Bathtub surround in marble-look porcelain tile with niche', 900, 1200],
  ['jacuzzi-tub-deck-marble-tile', 'bathroom', 'Jetted tub deck and surround finished in marble-look tile', 900, 1200],
  ['botanical-feature-wall-tile-bathroom', 'walls', 'Bathroom feature wall with botanical pattern tile', 900, 1200],
  ['powder-room-feature-wall-tile', 'walls', 'Powder room with patterned feature wall and marble-look tile', 900, 1200],
  ['marble-wall-tile-mosaic-band', 'walls', 'Marble-look wall tile with dark linear mosaic band', 900, 1200],
  ['wall-tile-mosaic-band-towel-rack', 'walls', 'Wall tile installation with mosaic accent band', 900, 1200],
  ['geometric-feature-wall-tile', 'walls', 'Geometric pattern tile feature wall with recessed niche', 900, 1200],
  ['subway-wall-tile-marble-floor', 'walls', 'Bathroom with white subway wall tile and marble-look plank floor', 900, 1200],
  ['kitchen-backsplash-grey-subway-tile', 'backsplash', 'Kitchen backsplash in grey subway tile with new countertops', 900, 1200],
  ['grey-tile-kitchen-backsplash', 'backsplash', 'Grey tile kitchen backsplash between wood cabinets and countertop', 900, 1200],
  ['star-pattern-decorative-floor-tile', 'flooring', 'Decorative star pattern porcelain floor tile', 900, 1200],
  ['patterned-porcelain-floor-installation', 'flooring', 'Patterned porcelain floor tile installation', 900, 1200],
  ['black-white-checkerboard-floor-tile', 'flooring', 'Black and white checkerboard floor tile installation', 900, 1200],
  ['checkerboard-tile-floor-glossy', 'flooring', 'Glossy black and white checkerboard tile floor', 900, 1200],
  ['marble-look-plank-floor-tile', 'flooring', 'Marble-look plank floor tile in a bathroom remodel', 900, 1200],
  ['marble-hexagon-floor-tile', 'flooring', 'Marble-look hexagon floor tile installed across an open room', 900, 1200],
  ['hexagon-marble-floor-installation', 'flooring', 'Marble-look hexagon floor tile installation', 900, 1200],
  ['octagon-dot-mosaic-floor', 'flooring', 'Octagon and dot mosaic floor tile', 900, 1200],
  ['octagon-mosaic-floor-tile', 'flooring', 'Octagon mosaic floor tile with grey accent dots', 900, 1200],
  ['wood-look-plank-tile-floor', 'flooring', 'Wood-look porcelain plank tile floor', 900, 1200],
  ['grey-wood-look-tile-floor', 'flooring', 'Grey wood-look plank tile floor', 900, 1200],
  ['grey-plank-tile-balcony-floor', 'flooring', 'Grey plank porcelain tile on a covered balcony', 900, 1200],
  ['wood-look-tile-porch-floor', 'flooring', 'Wood-look tile porch floor', 900, 1200],
  ['large-format-beige-floor-tile', 'flooring', 'Large-format beige floor tile installation', 900, 1200],
  ['beige-floor-tile-hallway', 'flooring', 'Beige floor tile in a hallway', 900, 1200],
  ['large-format-marble-floor-tile', 'flooring', 'Large-format marble-look floor tile installation', 900, 1200],
  ['marble-floor-tile-step-transition', 'flooring', 'Marble-look floor tile with step transitions', 900, 1200],
  ['bathroom-demolition-down-to-studs', 'process', 'Bathroom demolition down to the studs before remodel', 900, 1200],
  ['shower-waterproofing-membrane', 'process', 'Shower walls and pan waterproofed with a sheet membrane', 900, 1200],
  ['shower-waterproofing-detail', 'process', 'Waterproofing membrane seams and valve seal in a shower', 900, 1200],
  ['waterproofed-shower-pan-drain', 'process', 'Waterproofed shower pan with sloped drain before tile', 900, 1200],
  ['tile-leveling-system-installation', 'process', 'Wood-look floor tile installed with a leveling system', 900, 1200],
  ['floor-tile-leveling-clips', 'process', 'Floor tile leveling clips during installation', 900, 1200],
  ['floor-protection-during-remodel', 'process', 'Floor protection laid down during a remodel', 900, 1200],
];
